name: Main
on:
  push:

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install py dependencies
        run: |
          python -m pip install --upgrade pip
          pip install esptool
      - name: Install node dependencies
        run: |
          npm ci
      - name: Run tests
        run: |
          npm test
      - name: Build
        run: |
          npm run build
  deploy:
    needs:
      - test
    name: Deploy to npm
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch entire commit history.
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install deps
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Publish to NPM
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
